// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.14.0
// source: pce/mixer/pcemixer.proto

package pcemixerpb

import (
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type AddRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstNum  int64 `protobuf:"varint,1,opt,name=firstNum,proto3" json:"firstNum,omitempty"`
	SecondNum int64 `protobuf:"varint,2,opt,name=secondNum,proto3" json:"secondNum,omitempty"`
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pce_mixer_pcemixer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pce_mixer_pcemixer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_pce_mixer_pcemixer_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetFirstNum() int64 {
	if x != nil {
		return x.FirstNum
	}
	return 0
}

func (x *AddRequest) GetSecondNum() int64 {
	if x != nil {
		return x.SecondNum
	}
	return 0
}

type AddResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result int64 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pce_mixer_pcemixer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pce_mixer_pcemixer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_pce_mixer_pcemixer_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetResult() int64 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_pce_mixer_pcemixer_proto protoreflect.FileDescriptor

var file_pce_mixer_pcemixer_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x63, 0x65, 0x2f, 0x6d, 0x69, 0x78, 0x65, 0x72, 0x2f, 0x70, 0x63, 0x65, 0x6d,
	0x69, 0x78, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x63, 0x65, 0x6d,
	0x69, 0x78, 0x65, 0x72, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x46, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x66, 0x69, 0x72, 0x73, 0x74, 0x4e, 0x75, 0x6d, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x22, 0x25, 0x0a, 0x0b, 0x41, 0x64,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x32, 0x51, 0x0a, 0x08, 0x50, 0x63, 0x65, 0x4d, 0x69, 0x78, 0x65, 0x72, 0x12, 0x45, 0x0a,
	0x03, 0x41, 0x64, 0x64, 0x12, 0x14, 0x2e, 0x70, 0x63, 0x65, 0x6d, 0x69, 0x78, 0x65, 0x72, 0x2e,
	0x41, 0x64, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x70, 0x63, 0x65,
	0x6d, 0x69, 0x78, 0x65, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x11, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0b, 0x22, 0x06, 0x76, 0x31, 0x2f, 0x61, 0x64,
	0x64, 0x3a, 0x01, 0x2a, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x3b, 0x70, 0x63, 0x65, 0x6d, 0x69, 0x78,
	0x65, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pce_mixer_pcemixer_proto_rawDescOnce sync.Once
	file_pce_mixer_pcemixer_proto_rawDescData = file_pce_mixer_pcemixer_proto_rawDesc
)

func file_pce_mixer_pcemixer_proto_rawDescGZIP() []byte {
	file_pce_mixer_pcemixer_proto_rawDescOnce.Do(func() {
		file_pce_mixer_pcemixer_proto_rawDescData = protoimpl.X.CompressGZIP(file_pce_mixer_pcemixer_proto_rawDescData)
	})
	return file_pce_mixer_pcemixer_proto_rawDescData
}

var file_pce_mixer_pcemixer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pce_mixer_pcemixer_proto_goTypes = []interface{}{
	(*AddRequest)(nil),  // 0: pcemixer.AddRequest
	(*AddResponse)(nil), // 1: pcemixer.AddResponse
}
var file_pce_mixer_pcemixer_proto_depIdxs = []int32{
	0, // 0: pcemixer.PceMixer.Add:input_type -> pcemixer.AddRequest
	1, // 1: pcemixer.PceMixer.Add:output_type -> pcemixer.AddResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pce_mixer_pcemixer_proto_init() }
func file_pce_mixer_pcemixer_proto_init() {
	if File_pce_mixer_pcemixer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pce_mixer_pcemixer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pce_mixer_pcemixer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pce_mixer_pcemixer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pce_mixer_pcemixer_proto_goTypes,
		DependencyIndexes: file_pce_mixer_pcemixer_proto_depIdxs,
		MessageInfos:      file_pce_mixer_pcemixer_proto_msgTypes,
	}.Build()
	File_pce_mixer_pcemixer_proto = out.File
	file_pce_mixer_pcemixer_proto_rawDesc = nil
	file_pce_mixer_pcemixer_proto_goTypes = nil
	file_pce_mixer_pcemixer_proto_depIdxs = nil
}
