// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pcemixerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// PceMixerClient is the client API for PceMixer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PceMixerClient interface {
	// API for adding two integers
	//
	//
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
}

type pceMixerClient struct {
	cc grpc.ClientConnInterface
}

func NewPceMixerClient(cc grpc.ClientConnInterface) PceMixerClient {
	return &pceMixerClient{cc}
}

func (c *pceMixerClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, "/pcemixer.PceMixer/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PceMixerServer is the server API for PceMixer service.
// All implementations must embed UnimplementedPceMixerServer
// for forward compatibility
type PceMixerServer interface {
	// API for adding two integers
	//
	//
	Add(context.Context, *AddRequest) (*AddResponse, error)
	mustEmbedUnimplementedPceMixerServer()
}

// UnimplementedPceMixerServer must be embedded to have forward compatible implementations.
type UnimplementedPceMixerServer struct {
}

func (UnimplementedPceMixerServer) Add(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedPceMixerServer) mustEmbedUnimplementedPceMixerServer() {}

// UnsafePceMixerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PceMixerServer will
// result in compilation errors.
type UnsafePceMixerServer interface {
	mustEmbedUnimplementedPceMixerServer()
}

func RegisterPceMixerServer(s grpc.ServiceRegistrar, srv PceMixerServer) {
	s.RegisterService(&_PceMixer_serviceDesc, srv)
}

func _PceMixer_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PceMixerServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pcemixer.PceMixer/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PceMixerServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PceMixer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pcemixer.PceMixer",
	HandlerType: (*PceMixerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _PceMixer_Add_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pce/mixer/pcemixer.proto",
}
